<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>3.0.0</Version>
	<!-- Normalisiert Pfade für den Compiler -->
	<ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
	<Deterministic>true</Deterministic>

	<!-- Verhindert, dass Git-Hashes in die Datei-Info geschrieben werden -->
	<IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>

	<!-- WICHTIG für Single-File: Verhindert variierende Signaturen/Zeitstempel -->
	<CheckForInternalizeExplicitlySet>true</CheckForInternalizeExplicitlySet>
	  
	<PublishReadyToRun>false</PublishReadyToRun>
	  <!-- Betten Sie alle Quelldatei-Informationen in die PDB ein, 
       um lokale Dateisystem-Referenzen komplett zu eliminieren -->
	  <EmbedUntrackedSources>true</EmbedUntrackedSources>
	  <DebugType>embedded</DebugType>
  </PropertyGroup>

	<ItemGroup>
		<!-- Ersetzt den lokalen Pfad durch einen statischen Bezeichner -->
		<SourceRoot Include="$(MSBuildProjectDirectory)/" MappedPath="/src/"/>
	</ItemGroup>

</Project>
