name: build alpha

on:
  workflow_dispatch:

jobs:
  gitversion:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup GitVersion (install CLI)
        uses: gittools/actions/gitversion/setup@v4.2.0
        with:
          versionSpec: '6.5.1'

      - name: Show GitVersion config
        run: dotnet-gitversion /showConfig

      - name: Determine Version
        id: version_step # step id used as a reference for output values
        uses: gittools/actions/gitversion/execute@v4.2.0
        with:
          updateAssemblyInfo: true
  
