name: Merge Protection

on:
  workflow_call:
    inputs:
      allowed_branches:
        required: true
        type: string

env:
  test_ref: "feat/feat8"

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - name: Validation
        run: |
          echo "validate ${{ github.head_ref }}..."
          echo ${{ inputs.allowed_branches }}
          branches = ${{ inputs.allowed_branches }}
          echo $branches
          IFS=", "
          for branch in $branches;
          do
            echo $branch
            if echo "${{ env.test_ref }}" | grep ^$branch.*
            then
              echo "valid branch" && exit 0
            fi
          done
          echo "invalid branch" 
          echo "pull request only allowed from branches ${{ inputs.allowed_branches }}" && exit 1