name: Merge Protection

on:
  workflow_call:
    inputs:
      allowed_branches:
        required: true
        type: string

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - name: Validation
        run: |
          echo "validate ${{ github.head_ref }}..."
          for branch in ${allowed_branches[@]}
          do
            if echo "${{ github.head_ref }}" | grep ^$branch.*
            then
              echo "valid branch" && exit 0
            fi
          done
          echo "invalid branch" && exit 1