name: Dev Branch Protection

on:
  pull_request:
    branches: dev
env:
  dev_branch: "dev"
  input_branches: '["feat/", "fix/", "release/"]'

jobs:
  checking:
    runs-on: ubuntu-latest
    if: ${{ !startsWith(fromJson($env.input_branches), github.head_ref }}
    steps:
      - name: Abort
        run: |
          echo "pull request not allowed from this branch"
          exit 1
