name: Dev Branch Protection

on:
  push:
    branches: dev
env:
  dev_branch: "dev"
  input_branches: '["feat/", "fix/", "release/"]'
  input_branches2: ("feat/" "fix/" "release/")

jobs:
  checking:
    runs-on: ubuntu-latest
    steps:
      - name: is valid branch
        run: |
          echo ${input_branches2}
          for branch in ${env.input_branches2[@]}
          do
            if [[ github.head_ref == $branch* ]]
            then
              echo "valid branch" && exit 0
            fi
          done
          exit 1
          
