name: Automatic SemVer and Release Notes

on:
  workflow_call:
    inputs:
      dry_run:
        description: 'Run in dry-run mode (no actual release)'
        required: false
        default: false
        type: boolean
      sign:
        description: 'Create a certification bundle of the source code with cosign'
        required: false
        default: false
        type: boolean
    outputs: 
      version:
        description: "The new version in the project. (Could also be the same as before)"
        value: ${{ jobs.release.outputs.new_version_no }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    outputs:
      new_version_no: ${{ steps.semver.outputs.version }}
    env:
        GITHUB_TOKEN: ${{ secrets.PAT_GITHUB_WORKFLOWS }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Release
        id: semver
        uses: huggingface/semver-release-action@latest

      - name: Sign Source Code
        if: steps.semver.outputs.released == 'true' && inputs.sign == true
        env:
          TAG: ${{ steps.semver.outputs.tag }}
        run: |
          gh release download $TAG --archive=tar.gz --output source.tar.gz
          gh release download $TAG --archive=zip --output source.zip
          # creates a bundle file that containing a signatgure and certificate for later verification
          cosign sign-blob source.tar.gz --bundle source.tar.gz.bundle --yes
          cosign sign-blob source.zip --bundle source.zip.bundle --yes

      - name: Upload Certification Bundle
        if: steps.semver.outputs.released == 'true' && inputs.sign == true
        uses: softprops/action-gh-release@v2
        with:
          files: |
            source.tar.gz.bundle
            source.zip.bundle
          tag_name: ${{ steps.semver.outputs.tag }}